<?php require_once 'template/header.php';?>
<div class="container text-center pt-50 pb-50">
    <div class="loadingio-spinner-spin-f3vnkxn52tn"><div class="ldio-sgv279djvgs">
            <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
        </div></div>
    <style type="text/css">
        @keyframes ldio-sgv279djvgs {
            0% {
                opacity: 1;
                backface-visibility: hidden;
                transform: translateZ(0) scale(1.5,1.5);
            } 100% {
                  opacity: 0;
                  backface-visibility: hidden;
                  transform: translateZ(0) scale(1,1);
              }
        }
        .ldio-sgv279djvgs div > div {
            position: absolute;
            width: 12.48px;
            height: 12.48px;
            border-radius: 50%;
            background: #a00816;
            animation: ldio-sgv279djvgs 0.9803921568627451s linear infinite;
        }.ldio-sgv279djvgs div:nth-child(1) > div {
             left: 76px;
             top: 46px;
             animation-delay: -0.8578431372549019s;
         }
        .ldio-sgv279djvgs > div:nth-child(1) {
            transform: rotate(0deg);
            transform-origin: 82.24000000000001px 52.24px;
        }.ldio-sgv279djvgs div:nth-child(2) > div {
             left: 67px;
             top: 67px;
             animation-delay: -0.7352941176470588s;
         }
        .ldio-sgv279djvgs > div:nth-child(2) {
            transform: rotate(45deg);
            transform-origin: 73.24000000000001px 73.24000000000001px;
        }.ldio-sgv279djvgs div:nth-child(3) > div {
             left: 46px;
             top: 76px;
             animation-delay: -0.6127450980392157s;
         }
        .ldio-sgv279djvgs > div:nth-child(3) {
            transform: rotate(90deg);
            transform-origin: 52.24px 82.24000000000001px;
        }.ldio-sgv279djvgs div:nth-child(4) > div {
             left: 24px;
             top: 67px;
             animation-delay: -0.49019607843137253s;
         }
        .ldio-sgv279djvgs > div:nth-child(4) {
            transform: rotate(135deg);
            transform-origin: 30.240000000000002px 73.24000000000001px;
        }.ldio-sgv279djvgs div:nth-child(5) > div {
             left: 16px;
             top: 46px;
             animation-delay: -0.3676470588235294s;
         }
        .ldio-sgv279djvgs > div:nth-child(5) {
            transform: rotate(180deg);
            transform-origin: 22.240000000000002px 52.24px;
        }.ldio-sgv279djvgs div:nth-child(6) > div {
             left: 24px;
             top: 24px;
             animation-delay: -0.24509803921568626s;
         }
        .ldio-sgv279djvgs > div:nth-child(6) {
            transform: rotate(225deg);
            transform-origin: 30.240000000000002px 30.240000000000002px;
        }.ldio-sgv279djvgs div:nth-child(7) > div {
             left: 46px;
             top: 16px;
             animation-delay: -0.12254901960784313s;
         }
        .ldio-sgv279djvgs > div:nth-child(7) {
            transform: rotate(270deg);
            transform-origin: 52.24px 22.240000000000002px;
        }.ldio-sgv279djvgs div:nth-child(8) > div {
             left: 67px;
             top: 24px;
             animation-delay: 0s;
         }
        .ldio-sgv279djvgs > div:nth-child(8) {
            transform: rotate(315deg);
            transform-origin: 73.24000000000001px 30.240000000000002px;
        }
        .loadingio-spinner-spin-f3vnkxn52tn {
            width: 104px;
            height: 104px;
            display: inline-block;
            overflow: hidden;
            background: none;
        }
        .ldio-sgv279djvgs {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
        }
        .ldio-sgv279djvgs div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
    </style>
   <br>
    site dışında bir bağlantıya yönlendiriliyorsunuz lütfen bekleyiniz!<br>birazdan yönlendirileceksiniz.
</div>
<?php require_once 'template/footer.php';?>
